### ISSUE TITLE
SYS Password to Connect to SQLDeveloper

### ISSUE THREAD

**Issue by acel98-tech** [oracle/vagrant-boxes#141]
i did not take note of the sys,system,pdbadmin password for the database that was printed on install and it is not the same as the one for apex/ords. 
i connected to the database using **sqlplus / as sysdba** as this does not need a password. then, i used **alter user sys identified by password;** where password was my new password. i used this username(sys) and password(password) to make a new connection to sql developer but it says it is incorrect. 
can you tell me where i can find the the automatic password for the sys/ system acccounts?

**Comment by PaulNeumann** [comment]
Hi @acel98-tech,

Unless you changed the installation shell scripts, the automatic password for the SYS, SYSTEM and PDBADMIN database accounts is the same as the one that's used for the APEX admin account. So, if you have the password that was shown at the very end of the installation (`INSTALLER: Password:  xxxxxxxxxxxxx`), that's the same one used for SYS, SYSTEM and PDBADMIN.  The same password is also used for the APEX_LISTENER. APEX_PUBLIC_USER and APEX_REST_PUBLIC_USER database accounts.

To connect as SYS from SQL Developer, remember to choose SYSDBA in the Role drop-down when you set up your connection:

![image](https://user-images.githubusercontent.com/38871902/60747621-aa484900-9f43-11e9-9675-50e1a0d773d6.png)

I hope this helps!

**Comment by acel98-tech** [comment]
![gitproblem](https://user-images.githubusercontent.com/52584107/60747963-dfa66400-9f4e-11e9-9225-060b27041810.JPG)

Hi @PaulNeumann,

I do believe you are correct. However, I tried that password already multiple times and it fails. I was wondering if there is another password for just the database.

**Comment by PaulNeumann** [comment]
Hi @acel98-tech,

There isn't a separate password for just the database accounts.  But, as you noted, you can ssh to the box, then switch to the oracle user (`sudo su - oracle`), then connect to the database using `sqlplus / as sysdba` to change the passwords.

If you haven't done so already, I'd suggest changing the SYS password again, then verifying that it works using `sqlplus sys/password@XE as sysdba`.  If the password works in SQL*Plus, it should work in SQL Developer.

Have you tried to connect using SYSTEM, rather than SYS?  If so, did that work, or did you get the same error?

**Comment by acel98-tech** [comment]
@PaulNeumann 
I connected using `sqlplus sys/password@XE as sysdba` and I was able to connect with the password I changed it to. However, sqldeveloper is still unsuccessful. Could it be the new database connection name that has to be specific?

Also, yes I tried connecting with system and even changed the service name option to xePDB1 but this does not wor.

**Comment by PaulNeumann** [comment]
@acel98-tech,

The database connection parameters in the screenshot you posted look fine to me.  Do you also have Oracle Database XE installed on your host computer, or on another virtual machine running on your host?  The error message (ORA-01017) indicates that SQL Developer is successfully connecting to a database called XE, but it may not be connecting to the one you want (the database in the APEX Vagrant box).  If SQL Developer couldn't find //localhost:1521/XE at all, the error message would look like the following:

![image](https://user-images.githubusercontent.com/38871902/60776248-08ae2c80-a0e8-11e9-9a83-2e7491e9fe95.png)

If there are any other instances of Oracle Database XE running on your host or in another running VM, try shutting them down first, then restart the APEX Vagrant box and see whether SQL Developer can connect.

**Comment by PaulNeumann** [comment]
@MeanJadeComa ,

ORA-01017 means that SQL Developer and SQL*Plus successfully connected to **a** database, but it's possible that they didn't connect to the database in the Vagrant box.  A couple of things to look at are:

- Do have Oracle Database XE installed on your host computer, or on another virtual machine running on your host?  If so, try shutting down any other XE instances and see whether that helps.
- If your host is Windows, try opening an administrator command prompt and running `netstat -abno`. The output will probably be pretty long, but it should show you what process is listening on TCP port 1521. If it can't find the name of the listening process, you can use the PID (process ID) to look up the listening process in Task Manager. If the Vagrant box database is listening, the process name should be "VBoxHeadless.exe".

I hope this helps!

**Comment by MeanJadeComa** [comment]
Thanks Paul. I have fixed my issue. The problem was I had changed the password file and did not recreate the password file. After recreating the pw file all is well.

**Comment by PaulNeumann** [comment]
@MeanJadeComa,
Excellent! I'm glad it's working for you now.

**Comment by AnostDev** [comment]
After several times, I was able to connect to the database by using this command `sqlplus sys/password@orclpdb1 as sysdba` insteat of `sqlplus sys/password@XE as sysdba`. The difference is on the database SID. Since oracle 12.x Oracle uses what they call pluggable database which is a new way to make databases more scalable, so instead of using the default SID, you should use the service name (here the pluggable database identifier). You can find out more about pluggable databases in this blog https://blog.toadworld.com/2017/06/21/modularization-by-using-oracle-database-containers-and-pdbs-on-docker-engine

**Comment by gvenzl** [comment]
@acel98-tech, has your issue been fixed?

**Comment by gvenzl** [comment]
Closing due to lack of response.
