### ISSUE TITLE
Oracle User Password

### ISSUE THREAD

**Issue by rfevrier** [oracle/vagrant-boxes#155]
Greetings!

I am trying to install Java 8 on the box using this script:

**sudo apt-get install -y software-properties-common python-software-properties
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install oracle-java8-installer
echo "Setting environment variables for Java 8.."
sudo apt-get install -y oracle-java8-set-default**

I created a .sh file and copied it to the userscripts folder, but nothing happened.  I then ssh into the box to do a manual install, but I am bring asked for the password to the oracle user (see below).  What is the password?  I tried the DB password, but that didn't work either.

**[oracle@oracle-12201-vagrant ~]$ sudo apt-get install -y software-properties-common python-software-properties

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for oracle:** 

Regards

**Comment by PaulNeumann** [comment]
@rfevrier 
Let's try to get this working for you. Some background:
* Oracle Linux 7 uses yum, rather than apt, as its package manager.  The yum repository needed for installing Java 8 is already configured in the Vagrant box.
* Shell scripts in the userscripts directory need to have the appropriate shebang (`#!/bin/bash`) as the first line, so that the shell knows how to run them.
* Shell scripts in the userscripts directory run as root, so `sudo` isn't necessary.
* For a manual installation, it isn't necessary to change to the oracle user before installing packages. When you ssh to the box, you're connected as the vagrant user, which has password-less sudo privileges.
* Finally, to answer your initial question, the oracle user doesn't have a password.  The oracle user is created by the database preinstall package, and a password isn't configured.

To install Java 8 using a shell script in the userscripts directory, you could use the following:
```bash
#!/bin/bash
yum -y install java-1.8.0-openjdk
```
This will install the latest version of the Java 8 OpenJDK (currently 1.8.0.232).  You can name the script whatever you like, as long as it has a .sh extension.

To install it manually, ssh to the box and run the following:
```bash
sudo yum -y install java-1.8.0-openjdk
```
That's it!  The package will set the necessary environment variables.

If you need the Oracle JDK, and understand the licensing restrictions, you can download the necessary rpm from [here](https://www.oracle.com/technetwork/java/javase/downloads/index.html) and copy it to the same folder that contains the database installer zip file.  Then a shell script in the userscripts directory would look like:
```bash
#!/bin/bash
yum -y install /vagrant/jdk-8u231-linux-x64.rpm
```
Or, for a manual installation, ssh to the box and run the following:
```bash
sudo yum -y install /vagrant/jdk-8u231-linux-x64.rpm
```
I hope this helps.

Regards,
Paul
