### ISSUE TITLE
(OracleLinux/6): Unable to resolve dependency: user requested 'vagrant-vbguest (= 0.15.0)'

### ISSUE THREAD

**Issue by sanchitrk** [oracle/vagrant-boxes#52]
Installing vagrant-proxyconf Plugin...
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Fetching: vagrant-proxyconf-1.5.2.gem (100%)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-vbguest (= 0.15.0)'
<img width="626" alt="screen shot 2018-06-28 at 11 43 48 am" src="https://user-images.githubusercontent.com/12800711/42016287-a189f58e-7ac8-11e8-8072-b6cb428dde9f.png">

**Comment by AmedeeBulle** [comment]
We don't use/need vagrant-vbguest plugin, Oracle boxes have the VB Guest extensions pre-installed.

Did you upgrade vagrant recently?
If yes, you need to need to re-install / upgrade your plugin as well.

I believe this is unrelated to the Vagrantfile, it just happens because it does a `plugin install` which triggers the error.

**Comment by sanchitrk** [comment]
I guess I had updated vagrant to newer 2.0.1 recently. Thanks

**Comment by AmedeeBulle** [comment]
Thank you for letting us know.

I'll close this issue and #53 ; don't hesitate to reach us if you still have problems.
