### ISSUE TITLE
/vagrant/scripts/kubeadm-setup-master.sh giving no such file or directory

### ISSUE THREAD

**Issue by Aditya31398** [oracle/vagrant-boxes#68]
Vagrant up master worked successfully .
After this i typed vagrant ssh master
sudo -s
/vagrant/scripts/kubeadm-setup-master.sh
gave me 
bash: /vagrant/scripts/kubeadm-setup-master.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by AmedeeBulle** [comment]
This is an issue on Windows where git converts UNIX-style end-of-lines in DOS-style end-of-line based on the `core.autocrlf` git parameter.

You can avoid automatic conversion by setting `core.autocrlf` to `input` -- e.g.:
```
git config --global core.autocrlf input
```
(This needs to be done __before__ the `git clone`, it won't change already cloned repositories)

This issue is also addressed by #69 (waiting to be merged)

**Comment by Aditya31398** [comment]
Thanks, it worked.
