### ISSUE TITLE
the setPassword.sh script is not called from the install script

### ISSUE THREAD

**Issue by taseroth** [oracle/vagrant-boxes#89]
The copied setPassword.sh script is not called from the main install.sh.

I added the following line after line 82 to make it work:

`sudo su - oracle -c "/home/oracle/setPassword.sh $ORACLE_PWD`

I'm no script wizard, but this worked for me.

**Comment by PaulNeumann** [comment]
@taseroth The `setPassword.sh` script isn't needed during initial database setup. It's provided so that the SYS, SYSTEM and PDBADMIN passwords can be changed later, if desired.

Based on the `install.sh` line number you mention, I'm guessing that you're working with the 18.4.0-XE box, so I'll use that as an example, but all of the Oracle Database boxes work similarly. By default, the password for the database accounts is generated randomly (line 53 of `install.sh`):
```bash
export ORACLE_PWD=${ORACLE_PWD:-"`openssl rand -base64 8`1"}
```
This generated password is then copied to the installation configuration file (line 60 of `install.sh`):
```bash
sed -i -e "s|###ORACLE_PWD###|$ORACLE_PWD|g" /etc/sysconfig/oracle-xe-18c.conf
```
The installation configuration file is used to set the password for the database accounts during installation.

If you want to use a custom password, instead of a random one, you can do that by editing the environment section of the `Vagrantfile`. This section is near the end of the file (lines 56-60). The environment variable for the password is called `ORACLE_PWD`.  For example:
```ruby
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "ORACLE_CHARACTERSET" => "AL32UTF8",
       "SYSTEM_TIMEZONE"     => SYSTEM_TIMEZONE,
       "ORACLE_PWD"          => "MySecretPassword"
    }
```
When you specify a custom password in the `Vagrantfile`, it's used in place of the randomly-generated one. So, you can use either a random or a custom password without calling `setPassword.sh` from `install.sh`.

I hope this helps!

**Comment by taseroth** [comment]
@PaulNeumann first of all (I forgot to say so before): Big thanks for the vagrant script. I did help us a lot.

Also thanks for your timely response and explanation. 

Yes, I was using the 18.4.0-XE  script. For our development images I needed to add aditional users and added the nedded sql into the setPassword.sh and was wondering why the new users where not created. I kind of assumed that the setPassword.sh script would be part of the installation. 

If that is by design, than that is ok as well. Perhaps a little comment in the setPassword.sh informing about the fact?

But again, its no big deal and thanks again for your help

Bert

**Comment by PaulNeumann** [comment]
@taseroth The enhancement that allows the installer to run user-defined SQL and/or shell scripts after initial database setup is now available. If you clone this repository again (or merge the changes into your local repo), you'll see a new directory called `userscripts` under the `18.4.0-XE` directory. Any SQL and/or shell scripts you put into the `userscripts` directory before running `vagrant up` the first time will be run automatically. So, you could add a `create_users.sql` script containing the SQL that you need. The functionality is described in `README.md`, as well as in a file called `put_custom_scripts_here.txt` in the `userscripts` directory.

I hope this helps!

**Comment by gvenzl** [comment]
We have also added clarification as part of PR #111
