### ISSUE TITLE
oraclexe-18c EM Login does not work

### ISSUE THREAD

**Issue by nklamann** [oracle/vagrant-boxes#96]
I build a Pracle XE 18 c box straight from  the vagratnt file in '18.4.0-XE'. 
When I try ti log in  in EM I get several times the message box 'Critical Error LOGGIN_FAIL_ACCESSABILITY' and when I try to log in I get 'Critical Error fail to parse data returned by server'.

I have no prblem to log into the atabase with SQL Developer. 
Any ideas what is going on  here ?

**Comment by PaulNeumann** [comment]
@nklamann I haven't seen these error messages before, but EM Express should work. You should be able to connect to either the CDB or the PDB, using either the SYS or SYSTEM accounts. You shouldn't have to change anything within the VM or the database.

(For reference, I'm posting a link to [your thread in the XE community](https://community.oracle.com/thread/4199695) about this, because it includes screenshots.)

I'm guessing that you've already tried the following, but just in case...
- Try rebooting the box (`vagrant reload` or `vagrant halt`/`vagrant up`).
- Use the URL [https://localhost:5500/em](https://localhost:5500/em).
- To connect to the CDB, either leave the "Container Name" field on the login page blank, or use `CDB$ROOT`.
- To connect to the PDB, use `XEPDB1` for the "Container Name".
- To connect to the CDB as SYS, check the "as sysdba" checkbox on the login page. Otherwise, leave the  checkbox unchecked.

If none of this helps, then please post a little more information about your environment:
- Host OS (including version)
- The browser you're using (including version)
- Versions of VirtualBox and Vagrant
- Did you see any error or warning messages when you ran `vagrant up` the first time?

Thanks,
Paul

**Comment by nklamann** [comment]
Thanks @PaulNeumann 
I tried indeed these steps to no avail. I work under Windows 10, Version	10.0.17134 Build 17134
FF 65.0
VB Version 6.0.4 r128413 (Qt5.6.2)
Vagrant 2.2.3
Edge dose not show the Login screen but only a grey background. Internet Explorer works.
Seems to be a Flash/Browser/Windows - problem. Sigh.

**Comment by PaulNeumann** [comment]
@nklamann Thanks! This helps a lot.

I'm using a similar environment (Windows 10 Pro Version 1803, OS Build 17134.523; VirtualBox Version 6.0.4 r128413 (Qt5.6.2); Vagrant 2.2.3).  Here's what I see:
- Edge displays a grey background only (same as you)
- Internet Explorer runs EM Express fine (same as you)
- Firefox Beta, version 66.0b6 (64-bit), with Flash 32.0.0.114 (64-bit), runs EM Express fine
- Chrome Beta, version 73.0.3683.27 (64-bit), with Flash 32.0.0.142 (64-bit), runs EM Express fine

I'm running a slightly newer version of Firefox, but I don't know whether that matters. Here's what I'd suggest, if you have time:
- If you're not running Flash 32.0.0.114 in Firefox, try updating Flash.
- It's possible that a Firefox add-on (extension or plugin) is interfering with EM Express. Go through your Firefox add-ons and disable one at a time (except Flash). After disabling each add-on, try running EM Express again. If there's no difference, re-enable the add-on and disable the next one.

(It's also possible that a Firefox privacy/security setting is blocking EM Express, but I think that's less likely. My Firefox security settings are pretty restrictive, and EM Express works.)

I hope this helps!

Thanks,
Paul
